# Generated by Django 2.1.7 on 2019-03-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_shortcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.FloatField(default=0.0)),
                ('manual', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=50)),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seq_recommendations', to='server.Document')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sequencerecommendation',
            unique_together={('document', 'label', 'start_offset', 'end_offset')},
        ),
    ]
